### ISSUE TITLE
Implement forget password functionality

### ISSUE THREAD

**Issue by ChiranjeeviUppala** [PraveenSuggula/Brain-Squeezes#45]
#Estimation of time 
medium

This is linked to [#11](https://github.com/PraveenSuggula/Brain-Squeezes/issues/11#issue-1899861750)

**Comment by PraveenSuggula** [comment]
We have observed a dependency on email notification functionality #2. so moving its iteration for full fledged implementation.

**Comment by PraveenSuggula** [comment]
We have observed a dependency on email notification functionality https://github.com/PraveenSuggula/Brain-Squeezes/issues/2. so moving its iteration for full fledged implementation.
